/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xper_acq_comedi_ComediAnalogSWOutDevice */

#ifndef _Included_org_xper_acq_comedi_ComediAnalogSWOutDevice
#define _Included_org_xper_acq_comedi_ComediAnalogSWOutDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xper_acq_comedi_ComediAnalogSWOutDevice
 * Method:    nCreateTask
 * Signature: (Ljava/lang/String;I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_xper_acq_comedi_ComediAnalogSWOutDevice_nCreateTask
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_xper_acq_comedi_ComediAnalogSWOutDevice
 * Method:    nDestroy
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_comedi_ComediAnalogSWOutDevice_nDestroy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xper_acq_comedi_ComediAnalogSWOutDevice
 * Method:    nCreateChannels
 * Signature: (Ljava/nio/ByteBuffer;ISDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_comedi_ComediAnalogSWOutDevice_nCreateChannels
  (JNIEnv *, jobject, jobject, jint, jshort, jdouble, jdouble, jstring);

/*
 * Class:     org_xper_acq_comedi_ComediAnalogSWOutDevice
 * Method:    nWrite
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_comedi_ComediAnalogSWOutDevice_nWrite
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
