/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xper_acq_comedi_ComediDigitalPortOutDevice */

#ifndef _Included_org_xper_acq_comedi_ComediDigitalPortOutDevice
#define _Included_org_xper_acq_comedi_ComediDigitalPortOutDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xper_acq_comedi_ComediDigitalPortOutDevice
 * Method:    nCreateTask
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_xper_acq_comedi_ComediDigitalPortOutDevice_nCreateTask
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     org_xper_acq_comedi_ComediDigitalPortOutDevice
 * Method:    nDestroy
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_comedi_ComediDigitalPortOutDevice_nDestroy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xper_acq_comedi_ComediDigitalPortOutDevice
 * Method:    nWrite
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_comedi_ComediDigitalPortOutDevice_nWrite
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
