/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xper_acq_ni_NiAnalogSWOutDevice */

#ifndef _Included_org_xper_acq_ni_NiAnalogSWOutDevice
#define _Included_org_xper_acq_ni_NiAnalogSWOutDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xper_acq_ni_NiAnalogSWOutDevice
 * Method:    nCreateTask
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_xper_acq_ni_NiAnalogSWOutDevice_nCreateTask
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xper_acq_ni_NiAnalogSWOutDevice
 * Method:    nDestroy
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiAnalogSWOutDevice_nDestroy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xper_acq_ni_NiAnalogSWOutDevice
 * Method:    nCreateChannels
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;DD)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiAnalogSWOutDevice_nCreateChannels
  (JNIEnv *, jobject, jobject, jstring, jdouble, jdouble);

/*
 * Class:     org_xper_acq_ni_NiAnalogSWOutDevice
 * Method:    nWrite
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiAnalogSWOutDevice_nWrite
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
