/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xper_acq_ni_NiAnalogStreamingDevice */

#ifndef _Included_org_xper_acq_ni_NiAnalogStreamingDevice
#define _Included_org_xper_acq_ni_NiAnalogStreamingDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xper_acq_ni_NiAnalogStreamingDevice
 * Method:    nStart
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiAnalogStreamingDevice_nStart
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xper_acq_ni_NiAnalogStreamingDevice
 * Method:    nStop
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiAnalogStreamingDevice_nStop
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xper_acq_ni_NiAnalogStreamingDevice
 * Method:    nCreateTask
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_xper_acq_ni_NiAnalogStreamingDevice_nCreateTask
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xper_acq_ni_NiAnalogStreamingDevice
 * Method:    nDestroy
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiAnalogStreamingDevice_nDestroy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xper_acq_ni_NiAnalogStreamingDevice
 * Method:    nCreateChannels
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;DD)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiAnalogStreamingDevice_nCreateChannels
  (JNIEnv *, jobject, jobject, jstring, jdouble, jdouble);

/*
 * Class:     org_xper_acq_ni_NiAnalogStreamingDevice
 * Method:    nConfigTask
 * Signature: (Ljava/nio/ByteBuffer;DJ)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiAnalogStreamingDevice_nConfigTask
  (JNIEnv *, jobject, jobject, jdouble, jlong);

/*
 * Class:     org_xper_acq_ni_NiAnalogStreamingDevice
 * Method:    nScan
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_xper_acq_ni_NiAnalogStreamingDevice_nScan
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
