/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xper_acq_ni_NiDigitalPortOutDevice */

#ifndef _Included_org_xper_acq_ni_NiDigitalPortOutDevice
#define _Included_org_xper_acq_ni_NiDigitalPortOutDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xper_acq_ni_NiDigitalPortOutDevice
 * Method:    nCreateTask
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_xper_acq_ni_NiDigitalPortOutDevice_nCreateTask
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_xper_acq_ni_NiDigitalPortOutDevice
 * Method:    nDestroy
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiDigitalPortOutDevice_nDestroy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xper_acq_ni_NiDigitalPortOutDevice
 * Method:    nCreateChannels
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiDigitalPortOutDevice_nCreateChannels
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_xper_acq_ni_NiDigitalPortOutDevice
 * Method:    nWrite
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_xper_acq_ni_NiDigitalPortOutDevice_nWrite
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
