/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xper_util_OsUtil */

#ifndef _Included_org_xper_util_OsUtil
#define _Included_org_xper_util_OsUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xper_util_OsUtil
 * Method:    setAffinity
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_xper_util_OsUtil_setAffinity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_xper_util_OsUtil
 * Method:    getAffinity
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_xper_util_OsUtil_getAffinity
  (JNIEnv *, jclass);

/*
 * Class:     org_xper_util_OsUtil
 * Method:    getTimeOfDay
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_xper_util_OsUtil_getTimeOfDay
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
