from enum import Enum


class StimType(Enum):
    REGIME_ZERO = "REGIME_ZERO"
    REGIME_ZERO_2D = "REGIME_ZERO_2D"
    REGIME_ONE = "REGIME_ONE"
    REGIME_ONE_2D = "REGIME_ONE_2D"
    REGIME_TWO = "REGIME_TWO"
    REGIME_TWO_2D = "REGIME_TWO_2D"
    REGIME_THREE = "REGIME_THREE"
    REGIME_THREE_2D = "REGIME_THREE_2D"

