
% ======================== SET PLOT DEFAULTS ============================
set(0,'DefaultAxesFontName', 'Times New Roman', ...
    'DefaultTextFontName', 'Times New Roman', ...
    'DefaultFigureColor','k', ...
	'DefaultAxesTickLength',[0.03 0.03], ...
    'DefaultAxesTickDir','out', ...
    'DefaultAxesXGrid','on','DefaultAxesYGrid','on', ...
    'DefaultAxesColor', 'k', ...
    'DefaultAxesLineWidth', 2, ...
    'DefaultAxesDrawmode', 'fast', ...
    'DefaultAxesFontUnits', 'points', ...
    'DefaultAxesFontSize', 20, ...
    'DefaultAxesFontName', 'Times New Roman', ...
    'DefaultAxesGridLineStyle', ':', ...
    'DefaultAxesGridColor', [0.85 0.85 0.85], ...
    'DefaultAxesInterruptible', 'on', ...
    'DefaultAxesLayer', 'Bottom', ...
    'DefaultAxesNextPlot', 'replace', ...
    'DefaultAxesUnits', 'normalized', ...
    'DefaultAxesXcolor', [1 1 1], ...
    'DefaultAxesYcolor', [1 1 1], ...
    'DefaultAxesZcolor', [1 1 1], ...
    'DefaultAxesVisible', 'on', ...
    'DefaultLineColor', 'c', ...
    'DefaultLineLineStyle', '-', ...
    'DefaultLineLineWidth', 2, ...
    'DefaultLineMarker', 'none', ...
    'DefaultLineMarkerSize', 12, ...
    'DefaultTextColor', [1 1 1], ...
    'DefaultTextFontUnits', 'Points', ...
    'DefaultTextFontSize', 25, ...
    'DefaultTextColor', 'w', ...
    'DefaultTextFontName', 'Times New Roman', ...
    'DefaultTextVerticalAlignment', 'middle', ...
    'DefaultTextHorizontalAlignment', 'left');
% ======================================================================

