function updateInternalState(nTasks,gaInfo,conn)
    if gaInfo.isBubbles; isBubbles = 'true'; else isBubbles = 'false'; end
    
    str = {['<GenerationInfo>' ...
        char(10) char(9) '<genId>' num2str(gaInfo.genNum-1) '</genId>' ...
        char(10) char(9) '<taskCount>' num2str(nTasks) '</taskCount>' ...
        char(10) char(9) '<stimPerLinCount>' num2str(gaInfo.stimAndTrial.nStim) '</stimPerLinCount>' ...
        char(10) char(9) '<stimPerTrial>' num2str(gaInfo.stimAndTrial.nStimPerTrial) '</stimPerTrial>' ...
        char(10) char(9) '<repsPerStim>' num2str(gaInfo.stimAndTrial.nReps) '</repsPerStim>' ...
        char(10) char(9) '<enableFingerprinting>' num2str(gaInfo.enableFingerprinting) '</enableFingerprinting>' ...
        char(10) char(9) '<numFingerprintingStim>' num2str(gaInfo.stimAndTrial.nStimFingerprinting) '</numFingerprintingStim>' ...
        char(10) char(9) '<numFingerprintingRepsPerChunk>' num2str(gaInfo.stimAndTrial.nRepsFingerprintingPerChunk) '</numFingerprintingRepsPerChunk>' ...
        char(10) char(9) '<isBubblesPostHoc>' num2str(isBubbles) '</isBubblesPostHoc>' ...
        char(10) '</GenerationInfo>']};
    updateSqlTable(str,{'val'},'InternalState','where name = ''task_to_do_gen_ready''',conn);
end

