#!/bin/bash
source version
source paths

mysql --host=172.30.6.80 --user=xper_rw --password=up2nite $VERSION_GA << EOF
UPDATE SystemVar SET val=1 WHERE name='xper_eye_window_algorithm_base_window_size';
UPDATE SystemVar SET val=1 WHERE name='xper_eye_window_algorithm_initial_window_size';
UPDATE SystemVar SET val=1500 WHERE name='xper_slide_length';
UPDATE SystemVar SET val=250 WHERE name='xper_inter_slide_interval';
UPDATE SystemVar SET val=2000 WHERE name='xper_inter_trial_interval';
UPDATE SystemVar SET val=1 WHERE name='xper_slides_per_trial';
UPDATE SystemVar SET val=1 WHERE name='xper_fixation_point_color' AND arr_ind=0;
UPDATE SystemVar SET val=0 WHERE name='xper_fixation_point_color' AND arr_ind=1;
UPDATE SystemVar SET val=0 WHERE name='xper_fixation_point_color' AND arr_ind=2;
UPDATE SystemVar SET val='true' WHERE name='xper_do_empty_task';
UPDATE SystemVar SET val=200 WHERE name='xper_required_eye_in_and_hold_time';
UPDATE SystemVar SET val=150 WHERE name='xper_eye_monitor_out_time_threshold';
UPDATE SystemVar SET val=0.15 WHERE name='xper_background_color' AND arr_ind=0;
UPDATE SystemVar SET val=0.15 WHERE name='xper_background_color' AND arr_ind=1;
UPDATE SystemVar SET val=0.15 WHERE name='xper_background_color' AND arr_ind=2;
EOF

sudo -S <<< r2_allen cp $XPER_PROPERTIES_GA $DIST/xper.properties
sudo -S <<< r2_allen cp $XPER_PROPERTIES_GA $DIST/allen/xper.properties
cd $DIST/allen
java -jar fixcal_console.jar
