#!/bin/bash
source version
source paths
./SystemVars

mysql --host=172.30.6.80 --user=xper_rw --password=up2nite $VERSION_GA <<EOF
UPDATE SystemVar SET val=500 WHERE name='xper_slide_length';
UPDATE SystemVar SET val=4 WHERE name='xper_slides_per_trial';
UPDATE SystemVar SET val=200 WHERE name = 'xper_inter_slide_interval';
UPDATE SystemVar SET val=1000 WHERE name='xper_inter_trial_interval';
UPDATE SystemVar SET val=100 WHERE name='xper_streak_to_start_punishment';
UPDATE SystemVar SET val=0 WHERE name='xper_juice_bonus_probability';
UPDATE SystemVar SET val=3000 WHERE name='xper_punishment_delay_length';
EOF

sudo -S <<< r2_allen cp $XPER_PROPERTIES_GA $DIST/xper.properties
sudo -S <<< r2_allen cp $XPER_PROPERTIES_GA $DIST/allen/xper.properties
cd $DIST/allen
java -jar GAConsole.jar
