#!/bin/bash
source pathsProcedural

mysql --host=172.30.6.80 --user=xper_rw --password=up2nite allen_estimshape_$VERSION << EOF
DELETE from SystemVar where name = 'xper_left_iscan_eye_zero';
DELETE from SystemVar where name = 'xper_right_iscan_eye_zero';
DELETE from SystemVar where name = 'xper_left_iscan_mapping_algorithm_parameter';
DELETE from SystemVar where name = 'xper_right_iscan_mapping_algorithm_parameter';

INSERT INTO \`SystemVar\` (\`name\`, \`arr_ind\`, \`tstamp\`, \`val\`)
VALUES
    ('xper_right_iscan_mapping_algorithm_parameter', 3, 1097000000000340, '1'),
    ('xper_right_iscan_mapping_algorithm_parameter', 2, 1097000000000340, '0'),
    ('xper_right_iscan_mapping_algorithm_parameter', 1, 1097000000000340, '0'),
    ('xper_right_iscan_mapping_algorithm_parameter', 0, 1097000000000340, '1'),
    ('xper_left_iscan_mapping_algorithm_parameter', 0, 1097000000000340, '1'),
    ('xper_left_iscan_mapping_algorithm_parameter', 1, 1097000000000340, '0'),
    ('xper_left_iscan_mapping_algorithm_parameter', 2, 1097000000000340, '0'),
    ('xper_left_iscan_mapping_algorithm_parameter', 3, 1097000000000340, '1'),
    ('xper_right_iscan_eye_zero', 0, 1097000000000320, '0'),
    ('xper_right_iscan_eye_zero', 1, 1097000000000320, '0'),
    ('xper_left_iscan_eye_zero', 0, 1097000000000320, '0'),
    ('xper_left_iscan_eye_zero', 1, 1097000000000320, '0');
EOF
