#!/bin/bash
source version
source paths
./SystemVars

#Often VARYING SystemVars - HeadFixed now. 
mysql --host=172.30.6.61 --user=xper_rw --password=up2nite $VERSION_PROCEDURAL <<EOF
UPDATE SystemVar SET val=3000 WHERE name='xper_punishment_delay_length';
UPDATE SystemVar SET val=3000 WHERE name='xper_inter_trial_interval';
UPDATE SystemVar SET val='false' WHERE name='xper_nafc_show_answer';
UPDATE SystemVar SET val=0 WHERE name='xper_answer_length';
UPDATE SystemVar SET val='false' WHERE name='xper_nafc_repeat_incorrect_trials';
UPDATE SystemVar SET val='true' WHERE name='xper_nafc_repeat_sample_fail_trials';
UPDATE SystemVar SET val=2000 WHERE name='xper_sample_length';
UPDATE SystemVar SET val=15000 WHERE name='xper_time_allowed_for_initial_target_selection';
UPDATE SystemVar SET val=2000 WHERE name='xper_required_target_selection_hold_time';
UPDATE SystemVar SET val=1000 WHERE name='xper_streak_to_start_punishment';
UPDATE SystemVar SET val='RAND' WHERE name='xper_unget_policy';
UPDATE SystemVar SET val='true' WHERE name='xper_punish_sample_hold_fail';
UPDATE SystemVar SET val=2 WHERE name='xper_choice_correct_juice_multiplier';
UPDATE SystemVar SET val=1.0 WHERE name='xper_choice_correct_juice_multiplier_chance';
UPDATE SystemVar SET val=500 WHERE name='xper_blank_target_screen_display_time';
UPDATE SystemVar SET val=500 WHERE name='xper_required_eye_in_and_hold_time';
UPDATE SystemVar SET val=1 WHERE name='xper_eye_window_algorithm_base_window_size';
UPDATE SystemVar SET val=1 WHERE name='xper_eye_window_algorithm_initial_window_size';
UPDATE SystemVar SET val=15 WHERE name = 'xper_max_image_dimension_degrees';
UPDATE SystemVar SET val=60 WHERE name = 'xper_noise_rate';
EOF

sudo -S <<< r2_allen cp $XPER_PROPERTIES_PROCEDURAL $DIST/xper.properties
sudo -S <<< r2_allen cp $XPER_PROPERTIES_PROCEDURAL $DIST/allen/xper.properties
cd $DIST/allen
java -jar NAFCConsole.jar
