#!/bin/bash
source version
source paths

sudo -S <<< r2_allen cp $XPER_PROPERTIES_TWODVSTHREED $DIST/xper.properties
sudo -S <<< r2_allen cp $XPER_PROPERTIES_TWODVSTHREED $DIST/allen/xper.properties
cd $DIST/allen

java -jar TwoDVsThreeDTrialGenerator.jar

