#!/bin/bash
source version
source paths

sudo -S <<< Whedon101 cp $XPER_PROPERTIES_ISOGABOR $DIST/xper.properties
sudo -S <<< Whedon101 cp $XPER_PROPERTIES_ISOGABOR $DIST/allen/xper.properties
cd $DIST/allen

java -jar IsoGaborGenerator.jar "false" "false"

