#!/bin/bash
source version
source paths

START_RANK=1
END_RANK=10

sudo -S <<< Whedon101 cp $XPER_PROPERTIES_SHUFFLE $DIST/xper.properties
sudo -S <<< Whedon101 cp $XPER_PROPERTIES_SHUFFLE $DIST/allen/xper.properties
cd $DIST/allen

java -jar ShuffleTrialGenerator.jar $START_RANK $END_RANK

