#!/bin/bash
source version
source paths

sudo -S <<< Whedon101 cp $XPER_PROPERTIES_LIGHTNESS $DIST/xper.properties
sudo -S <<< Whedon101 cp $XPER_PROPERTIES_LIGHTNESS $DIST/allen/xper.properties
cd $DIST/allen

java -jar TwoDThreeDLightnessTrialGenerator.jar

