#!/bin/bash
source version
source paths

sudo -S <<< r2_allen cp $XPER_PROPERTIES_ISOGABOR $DIST/xper.properties
sudo -S <<< r2_allen cp $XPER_PROPERTIES_ISOGABOR $DIST/allen/xper.properties
cd $DIST/allen

java -jar IsoGaborGenerator.jar

