#!/bin/bash
source version
source paths

sudo -S <<< r2_allen cp $XPER_PROPERTIES_TWODTHREEDLIGHTNESS $DIST/xper.properties
sudo -S <<< r2_allen cp $XPER_PROPERTIES_TWODTHREEDLIGHTNESS $DIST/allen/xper.properties
cd $DIST/allen

java -jar TwoDThreeDLightnessTrialGenerator.jar

