#!/bin/bash
source version
VERSION=$VERSION_GA
PROPERTIES="xper.properties.ga"

#Defining paths for xper.properties versions
ESTIMSHAPE="/home/r2_allen/git/EStimShape"
SHELLSCRIPTS="$ESTIMSHAPE/xper-train/shellScripts"
XPER_PROPERTIES_GA="$SHELLSCRIPTS/xper.properties.ga"
DIST="$ESTIMSHAPE/xper-train/dist"








