#!/bin/bash
#All we need to do is change VERSION. 
VERSION=train_221020

#Defining paths for xper.properties versions
XPER_PROPERTIES_PSYCHOMETRIC="/home/r2_allen/Documents/EStimShape/"$VERSION"/shellScripts/xper.properties.psychometric"
XPER_PROPERTIES_FIXATION="/home/r2_allen/Documents/EStimShape/"$VERSION"/shellScripts/xper.properties.fixation"

DIST="/home/r2_allen/Documents/EStimShape/"$VERSION"/dist"
#DIST="/home/r2_allen/git/EStimShape/xper-train/dist"

#PSYCHOMETRIC PNG AND NOISEMAP PATHS
R2_PNGS="/home/r2_allen/Documents/EStimShape/"$VERSION"/pngs_"$VERSION
R2_PSYCHOMETRIC_PNGS="/home/r2_allen/Documents/EStimShape/"$VERSION"/pngs_"$VERSION"_psychometric"
M2_PNGS="m2_allen@m2_aliya:/home/m2_allen/Documents/pngs/pngs_"$VERSION
R2_PSYCHOMETRIC_NOISEMAPS="/home/r2_allen/Documents/EStimShape/"$VERSION"/noisemaps_"$VERSION"_psychometric"


#Replacing Database Declarations in all xper.properties versions. These sed commands are called everytime source paths is run. 
sed -i 's\jdbc.url=jdbc:mysql:.*\jdbc.url=jdbc:mysql://172.30.6.80/allen_estimshape_'$VERSION'\g' xper.properties.psychometric

#Rand Gen Paths
sed -i 's\generator.png_path.*\generator.png_path = /home/r2_allen/Documents/EStimShape/'$VERSION'/pngs_'$VERSION'\g' xper.properties.psychometric
sed -i 's\experiment.png_path.*\experiment.png_path = /home/m2_allen/Documents/pngs/pngs_'$VERSION'/pngs_'$VERSION'\g' xper.properties.psychometric
sed -i 's\generator.spec_path.*\generator.spec_path = /home/r2_allen/Documents/EStimShape/'$VERSION'/specs\g' xper.properties.psychometric


#Psychometric Paths
sed -i 's\generator.psychometric.png_path.*\generator.psychometric.png_path = /home/r2_allen/Documents/EStimShape/'$VERSION'/pngs_'$VERSION'_psychometric''\g' xper.properties.psychometric
sed -i 's\generator.psychometric.noisemap_path.*\generator.psychometric.noisemap_path = /home/r2_allen/Documents/EStimShape/'$VERSION'/noisemaps_'$VERSION'_psychometric''\g' xper.properties.psychometric
sed -i 's\generator.psychometric.spec_path.*\generator.psychometric.spec_path = /home/r2_allen/Documents/EStimShape/'$VERSION'/specs_'$VERSION'_psychometric''\g' xper.properties.psychometric
sed -i 's\experiment.psychometric.png_path.*\experiment.psychometric.png_path = /home/m2_allen/Documents/pngs/pngs_'$VERSION'/pngs_'$VERSION'_psychometric''\g' xper.properties.psychometric
sed -i 's\experiment.psychometric.noisemap_path.*\experiment.psychometric.noisemap_path = /home/m2_allen/Documents/pngs/pngs_'$VERSION'/noisemaps_'$VERSION'_psychometric''\g' xper.properties.psychometric









