#!/bin/bash
source version

#Replacing Database Declarations
sed -i 's\jdbc.url=jdbc:mysql:.*\jdbc.url=jdbc:mysql://172.30.6.80/allen_estimshape_'$VERSION'?rewriteBatchedStatements=true\g' xper.properties.procedural

#Defining paths for xper.properties versions
ESTIMSHAPE="/home/r2_allen/git/EStimShape"
SHELLSCRIPTS="$ESTIMSHAPE/xper-train/shellScripts"
XPER_PROPERTIES_PROCEDURAL="$SHELLSCRIPTS/xper.properties.procedural"
DIST="$ESTIMSHAPE/xper-train/dist"

#DEFINING BASE STIMULI DIR for Recording and Monkey Computer
R_STIMULI="$ESTIMSHAPE/xper-train/stimuli"
M_STIMULI="/home/m2_allen/Documents/stimuli/$VERSION"


#PROCEDURAL PATHS
R_PROCEDURAL="$R_STIMULI/procedural"
M_PROCEDURAL="$M_STIMULI/procedural"
M_RSYNC_PROCEDURAL="m2_allen@m2_aliya:/home/m2_allen/Documents/stimuli/$VERSION/procedural"

R_PNGS="$R_PROCEDURAL/pngs"
R_SPECS="$R_PROCEDURAL/specs"
R_NOISEMAPS="$R_PROCEDURAL/noisemaps"
M_PNGS="$M_PROCEDURAL/pngs"
M_SPECS="$M_PROCEDURAL/specs"
M_NOISEMAPS="$M_PROCEDURAL/noisemaps"

sed -i "s\generator.png_path.*\generator.png_path = $R_PNGS\g" xper.properties.procedural
sed -i "s\experiment.png_path.*\experiment.png_path = $M_PNGS\g" xper.properties.procedural
sed -i "s\generator.spec_path.*\generator.spec_path = $R_SPECS\g" xper.properties.procedural
sed -i "s\generator.noisemap_path.*\generator.noisemap_path = $R_NOISEMAPS\g" xper.properties.procedural
sed -i "s\experiment.noisemap_path.*\experiment.noisemap_path = $M_NOISEMAPS\g" xper.properties.procedural


#RFPLOT PATHS
R_RFPLOT="$R_STIMULI/rfplot"
M_RFPLOT="$M_STIMULI/rfplot"
R_RFPLOT_PNGS="$R_RFPLOT/pngs"
M_RFPLOT_PNGS="$M_RFPLOT/pngs"
M_RSYNC_RFPLOT="m2_allen@m2_aliya:/home/m2_allen/Documents/stimuli/$VERSION/rfplot"


sed -i "s\rfplot.png_library_path_generator.*\rfplot.png_library_path_generator = $R_RFPLOT_PNGS\g" xper.properties.procedural
sed -i "s\rfplot.png_library_path_experiment.*\rfplot.png_library_path_experiment = $M_RFPLOT_PNGS\g" xper.properties.procedural







