#!/bin/bash
source version

PROPERTIES="xper.properties.fixation"

#Replacing Database Declarations
sed -i 's\jdbc.url=jdbc:mysql:.*\jdbc.url=jdbc:mysql://172.30.6.80/allen_estimshape_'$VERSION'?rewriteBatchedStatements=true\g' $PROPERTIES

#Defining paths for xper.properties versions
ESTIMSHAPE="/home/r2_allen/git/EStimShape"
SHELLSCRIPTS="$ESTIMSHAPE/xper-train/shellScripts"
XPER_PROPERTIES_FIXATION="$SHELLSCRIPTS/xper.properties.fixation"
DIST="$ESTIMSHAPE/xper-train/dist"

#DEFINING BASE STIMULI DIR for Recording and Monkey Computer
R_STIMULI="$ESTIMSHAPE/xper-train/stimuli"
M_STIMULI="/home/m2_allen/Documents/stimuli/$VERSION"


#FIXATION PATHS
R_FIXATION="$R_STIMULI/fixation"
M_FIXATION="$M_STIMULI/fixation"
M_RSYNC_FIXATION="m2_allen@m2_aliya:/home/m2_allen/Documents/stimuli/$VERSION/fixation"

R_PNGS="$R_FIXATION/pngs"
R_SPECS="$R_FIXATION/specs"
M_PNGS="$M_FIXATION/pngs"
M_SPECS="$M_FIXATION/specs"

sed -i "s\generator.png_path.*\generator.png_path = $R_PNGS\g" $PROPERTIES
sed -i "s\experiment.png_path.*\experiment.png_path = $M_PNGS\g" $PROPERTIES
sed -i "s\generator.spec_path.*\generator.spec_path = $R_SPECS\g" $PROPERTIES







