#!/bin/bash
source version
VERSION=$VERSION_ISOGABOR
PROPERTIES="xper.properties.isogabor"

#Replacing Database Declarations
sed -i 's\jdbc.url=jdbc:mysql:.*\jdbc.url=jdbc:mysql://172.30.6.80/allen_isogabor_'$VERSION'?rewriteBatchedStatements=true\g' $PROPERTIES

#Defining paths for xper.properties versions
ESTIMSHAPE="/home/r2_allen/git/EStimShape"
SHELLSCRIPTS="$ESTIMSHAPE/xper-train/shellScripts"
XPER_PROPERTIES_ISOGABOR="$SHELLSCRIPTS/$PROPERTIES"
DIST="$ESTIMSHAPE/xper-train/dist"








