function saveOccluderToDb(occluder,descGenId,conn)
    colnames = {'id','descGenId','lb_x','lb_y','rt_x','rt_y','color_r','color_g','color_b'};
    tableName = 'StimObjData_occluder';

    id = getPosixTimeNow;

    insertIntoSqlTable({id,...
                        descGenId,...
                        occluder.leftBottom(1),...
                        occluder.leftBottom(2),...
                        occluder.rightTop(1),...
                        occluder.rightTop(2),...
                        occluder.color(1),...
                        occluder.color(2),...
                        occluder.color(3)},...
                colnames,tableName,conn);
end