package org.xper.allen.nafc.vo;

public enum NAFCTrialResult {
	INITIAL_EYE_IN_FAIL, EYE_IN_HOLD_FAIL, FIXATION_SUCCESS, 
	SLIDE_OK, TRIAL_COMPLETE, EYE_BREAK, 
	NO_MORE_TASKS, EXPERIMENT_STOPPING,
	SAMPLE_EYE_IN_HOLD_FAIL,
	TARGET_SELECTION_EYE_FAIL, TARGET_SELECTION_EYE_BREAK, TARGET_SELECTION_SUCCESS
}	
