function updateInternalState(nTasks,gaInfo,conn)
    str = {['<GenerationInfo>' ...
        char(10) char(9) '<genId>' num2str(gaInfo.genNum-1) '</genId>' ...
        char(10) char(9) '<taskCount>' num2str(nTasks) '</taskCount>' ...
        char(10) char(9) '<stimPerLinCount>' num2str(gaInfo.stimAndTrial.nStim) '</stimPerLinCount>' ...
        char(10) char(9) '<stimPerTrial>' num2str(gaInfo.stimAndTrial.nStimPerTrial) '</stimPerTrial>' ...
        char(10) char(9) '<repsPerStim>' num2str(gaInfo.stimAndTrial.nReps) '</repsPerStim>' ...
        char(10) char(9) '<useStereoRenderer>' bool2str(gaInfo.doStereo) '</useStereoRenderer>' ...
        char(10) '</GenerationInfo>']};
    updateSqlTable(str,{'val'},'InternalState','where name = ''task_to_do_gen_ready''',conn);
end

function str = bool2str(val)
    if val
        str = 'true';
    else
        str = 'false';
    end
end