package org.xper.allen.nafc.blockgen.procedural;

import org.springframework.jdbc.core.JdbcTemplate;
import org.xper.allen.app.estimshape.EStimShapeExperimentTrialGenerator;
import org.xper.allen.drawing.composition.AllenMStickSpec;
import org.xper.allen.drawing.composition.experiment.ProceduralMatchStick;
import org.xper.allen.drawing.composition.morph.PruningMatchStick;

import javax.sql.DataSource;
import javax.vecmath.Point3d;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;
import java.util.Set;

/**
 * NAFC trial where the sample has the tuned-for component deleted. Choices are the variant
 * (original shape with the tuned-for component intact), the delta (shape where the tuned-for
 * component was changed to a non-driving variant), and the deleted shape itself. Additional
 * procedural distractors beyond the first two are generated by morphing the deleted sample;
 * random distractors are produced per the parent class.
 */
public class EStimShapeVariantsDeletedNAFCStim extends EStimShapeVariantsNAFCStim {

    protected long deltaMStickStimSpecId;

    public static EStimShapeVariantsDeletedNAFCStim createSampledDeletedNAFCStim(
            EStimShapeExperimentTrialGenerator generator,
            ProceduralStimParameters parameters,
            boolean isEStimEnabled,
            Long eStimSpecId) {

        DataSource gaDataSource = generator.getGaDataSource();
        JdbcTemplate gaJDBCTemplate = new JdbcTemplate(gaDataSource);

        List<Long> variantIds = gaJDBCTemplate.queryForList(
                "SELECT DISTINCT variant_id FROM IncludedDeltas WHERE included = TRUE",
                Long.class
        );

        if (variantIds.isEmpty()) {
            throw new RuntimeException("No variants with included deltas found in IncludedDeltas table. " +
                    "Run the PlotVariantDeltas analysis pipeline first to populate this table.");
        }

        Random random = new Random();
        long variantId = variantIds.get(random.nextInt(variantIds.size()));

        return new EStimShapeVariantsDeletedNAFCStim(generator, parameters, variantId, isEStimEnabled, eStimSpecId);
    }

    public EStimShapeVariantsDeletedNAFCStim(EStimShapeExperimentTrialGenerator generator, ProceduralStimParameters parameters, Long variantId, boolean isEStimEnabled, Long eStimSpecId) {
        super(generator, parameters, variantId, isEStimEnabled, eStimSpecId);
        // Sample is built from the variant (its tuned-for comp is then deleted).
        baseMStickStimSpecId = variantId;
        deltaMStickStimSpecId = getDeltaIdFromVariantId(variantId);
    }

    private long getDeltaIdFromVariantId(Long variantId) {
        JdbcTemplate gaJDBCTemplate = new JdbcTemplate(gaDataSource);

        List<Long> deltaIds = gaJDBCTemplate.queryForList(
                "SELECT delta_id FROM IncludedDeltas WHERE variant_id = ? AND included = TRUE",
                new Object[]{variantId},
                Long.class
        );

        if (deltaIds.isEmpty()) {
            throw new RuntimeException("No included deltas found for variant_id: " + variantId);
        }

        Random random = new Random();
        return deltaIds.get(random.nextInt(deltaIds.size()));
    }

    @Override
    protected ProceduralMatchStick generateSample() {
        // Load the variant (intact) — this is both the source for deletion and the geometry
        // we use to compute where the noise circle should appear. Variant/delta trials place
        // the noise at the preserved comp's junction; we want the deleted trial's noise to
        // land at the same screen location so trial type can't be inferred from noise.
        AllenMStickSpec variantSpec = new AllenMStickSpec();
        PruningMatchStick variantMStick = new PruningMatchStick(noiseMapper);
        variantMStick.setProperties(sampleSize, texture, is2D(), 1.0);
        variantMStick.setStimColor(color);
        variantMStick.setRf(rfSource.getReceptiveField());
        variantMStick.genMatchStickFromFile(gaSpecPath + "/" + baseMStickStimSpecId + "_spec.xml");
        variantSpec.setMStickInfo(variantMStick, false);

        // Compute noise origin from the intact variant. checkInNoise both validates and
        // populates variantMStick.noiseOrigin; we reuse that on the deleted sample below.
        noiseMapper.checkInNoise(variantMStick, noiseComponentIndcs, 0.45);
        Point3d variantNoiseOrigin = variantMStick.getNoiseOrigin();

        // Pick a positioning anchor: the first variant component that isn't being deleted.
        // After deletion the preserved comp is gone, so positionShape can't use it.
        Set<Integer> toRemove = new HashSet<>(noiseComponentIndcs);
        Integer anchorInParent = null;
        for (Integer compId : variantMStick.getCompIds()) {
            if (compId != 0 && !toRemove.contains(compId)) {
                anchorInParent = compId;
                break;
            }
        }
        if (anchorInParent == null) {
            throw new RuntimeException("No non-preserved component available to anchor positioning for deleted sample (variantId=" + baseMStickStimSpecId + ")");
        }
        // removeComponent compacts indices: surviving comps keep their relative order, so the
        // child index equals the parent index minus the number of removed comps that came before it.
        int anchorInChild = anchorInParent;
        for (Integer removedComp : toRemove) {
            if (removedComp < anchorInParent) {
                anchorInChild--;
            }
        }

        PruningMatchStick sample = new PruningMatchStick(noiseMapper);
        sample.setProperties(sampleSize, texture, is2D(), 1.0);
        sample.setStimColor(color);
        sample.setRf(rfSource.getReceptiveField());
        sample.setPositioningAnchor(variantMStick, anchorInChild, anchorInParent);
        sample.genRemovedLimbsMatchStick(variantMStick, toRemove);

        // Carry the variant's noise origin onto the deleted sample so generateGaussianNoiseMapFor
        // renders the noise circle in the same world location as the variant/delta would.
        sample.setNoiseOrigin(variantNoiseOrigin);

        mSticks.setSample(sample);
        mStickSpecs.setSample(mStickToSpec(sample));

        return sample;
    }

    @Override
    protected void generateProceduralDistractors(ProceduralMatchStick sample) {
        // Distractor 0 = the variant (tuned-for component intact).
        if (numProceduralDistractors >= 1) {
            PruningMatchStick variantDistractor = new PruningMatchStick(noiseMapper);
            correctNoiseRadius(variantDistractor);
            variantDistractor.setProperties(choiceSize, texture, is2D(), 1.0);
            variantDistractor.setStimColor(color);
            variantDistractor.setMaxDiameterDegrees(maxSampleSize);
            variantDistractor.genMatchStickFromFile(gaSpecPath + "/" + baseMStickStimSpecId + "_spec.xml");
            variantDistractor.centerShape();
            mSticks.addProceduralDistractor(variantDistractor);
            mStickSpecs.addProceduralDistractor(mStickToSpec(variantDistractor));
        }

        // Distractor 1 = the paired delta (tuned-for component changed to a non-driver).
        if (numProceduralDistractors >= 2) {
            PruningMatchStick deltaDistractor = new PruningMatchStick(noiseMapper);
            correctNoiseRadius(deltaDistractor);
            deltaDistractor.setProperties(choiceSize, texture, is2D(), 1.0);
            deltaDistractor.setStimColor(color);
            deltaDistractor.setMaxDiameterDegrees(maxSampleSize);
            deltaDistractor.genMatchStickFromFile(gaSpecPath + "/" + deltaMStickStimSpecId + "_spec.xml");
            deltaDistractor.centerShape();
            mSticks.addProceduralDistractor(deltaDistractor);
            mStickSpecs.addProceduralDistractor(mStickToSpec(deltaDistractor));
        }

        // Any additional procedural distractors are morph-based, generated from the deleted sample.
        for (int i = 0; i < numProceduralDistractors - 2; i++) {
            ProceduralMatchStick proceduralDistractor = new ProceduralMatchStick(noiseMapper);
            correctNoiseRadius(proceduralDistractor);
            proceduralDistractor.setProperties(choiceSize, texture, is2D(), 1.0);
            proceduralDistractor.setStimColor(color);
            proceduralDistractor.setMaxDiameterDegrees(maxSampleSize);
            proceduralDistractor.genNewComponentsMatchStick(sample, morphComponentIndcs, parameters.morphMagnitude, 0.5, true, proceduralDistractor.maxAttempts, noiseComponentIndcs);
            mSticks.addProceduralDistractor(proceduralDistractor);
            mStickSpecs.addProceduralDistractor(mStickToSpec(proceduralDistractor));
        }
    }

    @Override
    protected void assignLabels() {
        labels.setSample(new LinkedList<>(Arrays.asList("sample")));
        labels.setMatch(new LinkedList<>(Arrays.asList("match")));
        for (int i = 0; i < numProceduralDistractors; i++) {
            if (i == 0) {
                labels.addProceduralDistractor(new LinkedList<>(Arrays.asList("variant")));
            } else if (i == 1) {
                labels.addProceduralDistractor(new LinkedList<>(Arrays.asList("delta")));
            } else {
                labels.addProceduralDistractor(new LinkedList<>(Arrays.asList("procedural")));
            }
        }
        for (int i = 0; i < numRandDistractors; i++) {
            labels.addRandDistractor(new LinkedList<>(Arrays.asList("rand")));
        }
    }
}
